version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/Users
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
